-- =============================================================
-- Movie Explorer Master Schema (existing + planned)
-- =============================================================
-- Reader guide:
-- 1) SCHEMA 1/3: Core application model (users, social, chat, review)
-- 2) SCHEMA 2/3: Film mapping and directors
-- 3) SCHEMA 3/3: Planned recommendation model and user weights
-- 4) INDEX blocks: grouped by entity for easier review
--
-- Why this file exists:
-- - It is a full model snapshot for human review (portfolio/recruiter friendly).
-- - It also doubles as a technical validation script when executed in psql.
--
-- Optional technical usage:
-- Run full script:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db-schema-master.sql
--
-- Toggle controls:
--   -v APPLY_SCHEMA=1|0
--   -v APPLY_INDEXES=1|0
--   -v IDX_USERS=1|0 -v IDX_CHATS=1|0 -v IDX_WATCHLIST=1|0
--   -v IDX_FRIENDS=1|0 -v IDX_NOTIFICATIONS=1|0 -v IDX_REVIEWS=1|0
--   -v IDX_DIRECTORS=1|0 -v IDX_RECOMMENDATION=1|0
--
-- Example (run only recommendation indexes):
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -v APPLY_SCHEMA=0 -v APPLY_INDEXES=1 -v IDX_USERS=0 -v IDX_CHATS=0 -v IDX_WATCHLIST=0 -v IDX_FRIENDS=0 -v IDX_NOTIFICATIONS=0 -v IDX_REVIEWS=0 -v IDX_DIRECTORS=0 -v IDX_RECOMMENDATION=1 -f db-schema-master.sql

-- -----------------------------
-- Default toggle values
-- -----------------------------
\if :{?APPLY_SCHEMA}
\else
\set APPLY_SCHEMA 1
\endif

\if :{?APPLY_INDEXES}
\else
\set APPLY_INDEXES 1
\endif

\if :{?IDX_USERS}
\else
\set IDX_USERS 1
\endif

\if :{?IDX_CHATS}
\else
\set IDX_CHATS 1
\endif

\if :{?IDX_WATCHLIST}
\else
\set IDX_WATCHLIST 1
\endif

\if :{?IDX_FRIENDS}
\else
\set IDX_FRIENDS 1
\endif

\if :{?IDX_NOTIFICATIONS}
\else
\set IDX_NOTIFICATIONS 1
\endif

\if :{?IDX_REVIEWS}
\else
\set IDX_REVIEWS 1
\endif

\if :{?IDX_DIRECTORS}
\else
\set IDX_DIRECTORS 1
\endif

\if :{?IDX_RECOMMENDATION}
\else
\set IDX_RECOMMENDATION 1
\endif

\if :APPLY_SCHEMA

\echo '=== [SCHEMA 1/3] Core tables (V1..V4) ==='

-- users
create table if not exists users (
    id bigint generated by default as identity,
    username varchar(50) not null,
    email varchar(100) not null,
    password varchar(255) not null,
    role varchar(255) check (role in ('ROLE_USER', 'ROLE_ADMIN')),
    primary key (id),
    constraint unique_email unique (email)
);

-- chats
create table if not exists chats (
    id bigint generated by default as identity,
    primary key (id)
);

-- watchlist
create table if not exists watchlist (
    user_id bigint not null,
    primary key (user_id),
    constraint fk_watchlist_user foreign key (user_id) references users(id)
);

-- legacy watchlist split tables
create table if not exists watchlist_movies (
    watchlist_id bigint not null,
    movie_id bigint,
    constraint fk_watchlist_movies foreign key (watchlist_id) references watchlist(user_id)
);

create table if not exists watchlist_series (
    watchlist_id bigint not null,
    series_id bigint,
    constraint fk_watchlist_series foreign key (watchlist_id) references watchlist(user_id)
);

-- friends
create table if not exists friends (
    user1_id bigint not null,
    user2_id bigint not null,
    created_at timestamp(6) not null,
    status varchar(255) not null check (status in ('PENDING', 'ACCEPTED', 'BLOCKED')),
    primary key (user1_id, user2_id),
    constraint fk_friends_user1 foreign key (user1_id) references users(id),
    constraint fk_friends_user2 foreign key (user2_id) references users(id)
);

-- chat participants
create table if not exists chat_participants (
    chat_id bigint not null,
    user_id bigint not null,
    primary key (chat_id, user_id),
    constraint fk_chat_participants_chat foreign key (chat_id) references chats(id),
    constraint fk_chat_participants_user foreign key (user_id) references users(id)
);

-- messages
create table if not exists messages (
    id bigint generated by default as identity,
    chat_id bigint not null,
    sender_id bigint not null,
    content varchar(255) not null,
    is_read boolean not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint fk_messages_chat foreign key (chat_id) references chats(id),
    constraint fk_messages_sender foreign key (sender_id) references users(id)
);

-- notifications
create table if not exists notifications (
    id bigint generated by default as identity,
    user_id bigint not null,
    type varchar(255) not null,
    related_id bigint not null,
    message varchar(255) not null,
    is_read boolean not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint fk_notifications_user foreign key (user_id) references users(id)
);

-- review
create table if not exists review (
    id bigint generated by default as identity,
    content varchar(2000) not null,
    film_id bigint not null,
    type varchar(50) not null,
    score bigint,
    answer_to_id bigint,
    reply_count bigint not null default 0,
    user_id bigint not null,
    created_at timestamp(6) default current_timestamp,
    season_number int default null,
    episode_number int default null,
    primary key (id),
    constraint fk_review_user foreign key (user_id) references users(id),
    constraint fk_review_parent foreign key (answer_to_id) references review(id)
);

-- vote
create table if not exists vote (
    id bigint generated by default as identity,
    user_id bigint not null,
    review_id bigint not null,
    vote_value int not null,
    primary key (id),
    constraint fk_vote_user foreign key (user_id) references users(id),
    constraint fk_vote_review foreign key (review_id) references review(id),
    constraint uq_vote_user_review unique (user_id, review_id)
);

\echo '=== [SCHEMA 2/3] Film and director tables (V5..V6) ==='

-- film
create table if not exists film (
    internal_id bigint generated by default as identity,
    film_id bigint not null,
    title varchar(255),
    rating double precision,
    date date,
    background_img varchar(255),
    type varchar(50) not null,
    primary key (internal_id),
    constraint uq_film_tmdb_type unique (film_id, type)
);

-- normalized watchlist items
create table if not exists watchlist_items (
    watchlist_id bigint not null,
    internal_film_id bigint not null,
    primary key (watchlist_id, internal_film_id),
    constraint fk_watchlist_items_watchlist foreign key (watchlist_id) references watchlist(user_id),
    constraint fk_watchlist_items_film foreign key (internal_film_id) references film(internal_id)
);

-- directors
create table if not exists director (
    director_id bigint not null,
    name varchar(255) not null,
    primary key (director_id)
);

create table if not exists director_film (
    director_id bigint not null,
    internal_film_id bigint not null,
    primary key (director_id, internal_film_id),
    constraint fk_director_film_director foreign key (director_id) references director(director_id),
    constraint fk_director_film_film foreign key (internal_film_id) references film(internal_id)
);

\echo '=== [SCHEMA 3/3] Planned recommendation tables ==='

-- user recommendation baseline
create table if not exists user_film_reference (
    user_id bigint not null,
    primary key (user_id),
    constraint fk_user_film_reference_user foreign key (user_id) references users(id)
);

-- reference dimensions
create table if not exists genre (
    id bigint not null,
    name varchar(255) not null,
    type varchar(255) not null,
    primary key (id)
);

create table if not exists keyword (
    keyword_id bigint not null,
    name varchar(255) not null,
    type varchar(255) not null,
    primary key (keyword_id)
);

-- recommendation joins
create table if not exists film_genre (
    internal_film_id bigint not null,
    genre_id bigint not null,
    primary key (internal_film_id, genre_id),
    constraint fk_film_genre_film foreign key (internal_film_id) references film(internal_id),
    constraint fk_film_genre_genre foreign key (genre_id) references genre(id)
);

create table if not exists film_keyword (
    internal_film_id bigint not null,
    keyword_id bigint not null,
    primary key (internal_film_id, keyword_id),
    constraint fk_film_keyword_film foreign key (internal_film_id) references film(internal_id),
    constraint fk_film_keyword_keyword foreign key (keyword_id) references keyword(keyword_id)
);

create table if not exists recommendation (
    film_id bigint not null,
    recommended_film_id bigint not null,
    primary key (film_id, recommended_film_id),
    constraint fk_recommendation_film foreign key (film_id) references film(internal_id),
    constraint fk_recommendation_recommended_film foreign key (recommended_film_id) references film(internal_id)
);

-- user weights (composite PKs)
create table if not exists user_director_weight (
    user_id bigint not null,
    director_id bigint not null,
    weight bigint not null,
    primary key (user_id, director_id),
    constraint fk_user_director_weight_user foreign key (user_id) references user_film_reference(user_id),
    constraint fk_user_director_weight_director foreign key (director_id) references director(director_id)
);

create table if not exists user_genre_weight (
    user_id bigint not null,
    genre_id bigint not null,
    weight bigint not null,
    type varchar(255) not null,
    primary key (user_id, genre_id),
    constraint fk_user_genre_weight_user foreign key (user_id) references user_film_reference(user_id),
    constraint fk_user_genre_weight_genre foreign key (genre_id) references genre(id)
);

create table if not exists user_keyword_weight (
    user_id bigint not null,
    keyword_id bigint not null,
    weight bigint not null,
    type varchar(255) not null,
    primary key (user_id, keyword_id),
    constraint fk_user_keyword_weight_user foreign key (user_id) references user_film_reference(user_id),
    constraint fk_user_keyword_weight_keyword foreign key (keyword_id) references keyword(keyword_id)
);

\endif

\if :APPLY_INDEXES

\if :IDX_USERS
\echo '=== [INDEXES] users ==='
create index if not exists idx_user_email on users (email);
create index if not exists idx_user_id on users (id);
\endif

\if :IDX_CHATS
\echo '=== [INDEXES] chats/messages ==='
create index if not exists idx_chat on chats (id);
create index if not exists idx_chat_id on messages (chat_id, created_at desc);
\endif

\if :IDX_WATCHLIST
\echo '=== [INDEXES] watchlist ==='
create index if not exists idx_watchlist_user_id on watchlist (user_id);
create index if not exists idx_watchlist_items_watchlist on watchlist_items (watchlist_id);
create index if not exists idx_watchlist_items_film on watchlist_items (internal_film_id);
\endif

\if :IDX_FRIENDS
\echo '=== [INDEXES] friends ==='
create index if not exists idx_friend_user_status on friends (user1_id, status);
create index if not exists idx_friend_friend_status on friends (user2_id, status);
create index if not exists idx_friend_user_created_at on friends (user1_id, created_at desc);
\endif

\if :IDX_NOTIFICATIONS
\echo '=== [INDEXES] notifications ==='
create index if not exists idx_notification_user_id on notifications (user_id, created_at desc);
\endif

\if :IDX_REVIEWS
\echo '=== [INDEXES] reviews/votes ==='
create index if not exists idx_review_film_type_created on review (film_id, type, created_at desc);
create index if not exists idx_review_user_created on review (user_id, created_at desc);
create index if not exists idx_review_film_episode on review (film_id, type, season_number, episode_number);
create index if not exists idx_vote_user on vote (user_id);
create index if not exists idx_vote_review on vote (review_id);
\endif

\if :IDX_DIRECTORS
\echo '=== [INDEXES] directors ==='
create index if not exists idx_director_name on director (name);
create index if not exists idx_director_film_film on director_film (internal_film_id);
\endif

\if :IDX_RECOMMENDATION
\echo '=== [INDEXES] recommendation ==='
create index if not exists idx_film_genre_genre on film_genre (genre_id);
create index if not exists idx_film_keyword_keyword on film_keyword (keyword_id);
create index if not exists idx_user_director_weight_user on user_director_weight (user_id);
create index if not exists idx_user_director_weight_director on user_director_weight (director_id);
create index if not exists idx_user_genre_weight_user on user_genre_weight (user_id);
create index if not exists idx_user_genre_weight_genre on user_genre_weight (genre_id);
create index if not exists idx_user_keyword_weight_user on user_keyword_weight (user_id);
create index if not exists idx_user_keyword_weight_keyword on user_keyword_weight (keyword_id);
\endif

\endif