
    create table chat_participants (
        chat_id bigint not null,
        user_id bigint not null,
        primary key (chat_id, user_id)
    );

    create table chats (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table friends (
        created_at timestamp(6) not null,
        user1_id bigint not null,
        user2_id bigint not null,
        status varchar(255) not null check (status in ('PENDING','ACCEPTED','BLOCKED')),
        primary key (user1_id, user2_id)
    );

    create table messages (
        is_read boolean not null,
        chat_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        sender_id bigint not null,
        content varchar(255) not null,
        primary key (id)
    );

    create table notifications (
        is_read boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        related_id bigint not null,
        user_id bigint not null,
        message varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        username varchar(50) not null,
        email varchar(100) not null,
        password varchar(255) not null,
        role varchar(255) check (role in ('ROLE_USER','ROLE_ADMIN')),
        primary key (id),
        constraint unique_email unique (email)
    );

    create table watchlist (
        user_id bigint not null,
        primary key (user_id)
    );

    create table watchlist_movies (
        movie_id bigint,
        watchlist_id bigint not null
    );

    create table watchlist_series (
        series_id bigint,
        watchlist_id bigint not null
    );

    create index idx_chat 
       on chats (id);

    create index idx_friend_user_status 
       on friends (user1_id, status);

    create index idx_friend_friend_status 
       on friends (user2_id, status);

    create index idx_friend_user_created_at 
       on friends (user1_id, created_at desc);

    create index idx_chat_id 
       on messages (chat_id, created_at desc);

    create index idx_notification_user_id 
       on notifications (user_id, created_at desc);

    create index idx_user_email 
       on users (email);

    create index idx_user_id 
       on users (id);

    create index idx_watchlist_user_id 
       on watchlist (user_id);

    alter table if exists chat_participants 
       add constraint FKbhdyxo0ndtbs1t49l28y21rkw 
       foreign key (user_id) 
       references users;

    alter table if exists chat_participants 
       add constraint FKn4feij8janlba38q59kl2ebgg 
       foreign key (chat_id) 
       references chats;

    alter table if exists friends 
       add constraint FKixmq3ir3069oq850dloi7kr3t 
       foreign key (user1_id) 
       references users;

    alter table if exists friends 
       add constraint FKt5nty8dt2595lp0j0erwe4655 
       foreign key (user2_id) 
       references users;

    alter table if exists messages 
       add constraint FK64w44ngcpqp99ptcb9werdfmb 
       foreign key (chat_id) 
       references chats;

    alter table if exists messages 
       add constraint FK4ui4nnwntodh6wjvck53dbk9m 
       foreign key (sender_id) 
       references users;

    alter table if exists notifications 
       add constraint FK9y21adhxn0ayjhfocscqox7bh 
       foreign key (user_id) 
       references users;

    alter table if exists watchlist 
       add constraint FKden7i83qo2swnr5br4wgc5r7j 
       foreign key (user_id) 
       references users;

    alter table if exists watchlist_movies 
       add constraint FK4m82mvvbv3ifc19vdrvax6laj 
       foreign key (watchlist_id) 
       references watchlist;

    alter table if exists watchlist_series 
       add constraint FK42sm1s5drrqh8xsi05l6nbxrp 
       foreign key (watchlist_id) 
       references watchlist;
