-- Genre seeding reference tables (recommendation ingestion)
-- Structural decision: use new tables `genres`/`film_genres` so Phase 1 ingestion can seed best-effort genres
-- without coupling to the existing legacy `genre`/`film_genre` enrichment schema.

create table if not exists genres (
    id bigint generated by default as identity primary key,
    tmdb_genre_id int not null,
    name varchar(255) not null,
    film_type varchar(50) not null,
    constraint uq_genres_tmdb_type unique (tmdb_genre_id, film_type)
);

create index if not exists idx_genres_tmdb_type on genres (tmdb_genre_id, film_type);

create table if not exists film_genres (
    film_internal_id bigint not null,
    genre_id bigint not null,
    primary key (film_internal_id, genre_id),
    constraint fk_film_genres_film foreign key (film_internal_id) references film(internal_id),
    constraint fk_film_genres_genre foreign key (genre_id) references genres(id)
);

create index if not exists idx_film_genres_genre on film_genres (genre_id);