-- Reviews table
create table review (
    id bigint generated by default as identity,
    content varchar(2000) not null,
    film_id bigint not null,
    type varchar(50) not null,
    score bigint,
    answer_to_id bigint,
    reply_count bigint not null default 0,
    user_id bigint not null,
    created_at timestamp(6) default current_timestamp,
    primary key (id),
    constraint fk_review_user foreign key (user_id) references users(id),
    constraint fk_review_parent foreign key (answer_to_id) references review(id)
);

create index idx_review_film_type_created on review (film_id, type, created_at desc);
create index idx_review_user_created on review (user_id, created_at desc);

-- Votes table
create table vote (
    id bigint generated by default as identity,
    user_id bigint not null,
    review_id bigint not null,
    vote_value int not null,
    primary key (id),
    constraint fk_vote_user foreign key (user_id) references users(id),
    constraint fk_vote_review foreign key (review_id) references review(id),
    constraint uq_vote_user_review unique (user_id, review_id)
);

create index idx_vote_user on vote (user_id);
create index idx_vote_review on vote (review_id);
