-- Film mapping table (internal id + TMDB id)
create table if not exists film (
    internal_id bigint generated by default as identity primary key,
    film_id bigint not null,
    title varchar(255),
    rating double precision,
    date date,
    background_img varchar(255),
    type varchar(50) not null
);

create unique index if not exists uq_film_tmdb_type on film (film_id, type);

-- Watchlist items (internal film id mapping)
create table if not exists watchlist_items (
    watchlist_id bigint not null,
    internal_film_id bigint not null,
    primary key (watchlist_id, internal_film_id),
    constraint fk_watchlist_items_watchlist foreign key (watchlist_id) references watchlist,
    constraint fk_watchlist_items_film foreign key (internal_film_id) references film
);

create index if not exists idx_watchlist_items_watchlist on watchlist_items (watchlist_id);
create index if not exists idx_watchlist_items_film on watchlist_items (internal_film_id);

-- Backfill film table from legacy watchlist tables
insert into film (film_id, type)
select distinct movie_id, 'MOVIE'
from watchlist_movies
where movie_id is not null
on conflict (film_id, type) do nothing;

insert into film (film_id, type)
select distinct series_id, 'SERIES'
from watchlist_series
where series_id is not null
on conflict (film_id, type) do nothing;

-- Backfill watchlist_items from legacy watchlist tables
insert into watchlist_items (watchlist_id, internal_film_id)
select wm.watchlist_id, f.internal_id
from watchlist_movies wm
join film f on f.film_id = wm.movie_id and f.type = 'MOVIE'
on conflict do nothing;

insert into watchlist_items (watchlist_id, internal_film_id)
select ws.watchlist_id, f.internal_id
from watchlist_series ws
join film f on f.film_id = ws.series_id and f.type = 'SERIES'
on conflict do nothing;
